### ISSUE TITLE
Demo contents are not shown and Editor widget is not displayed well.

### ISSUE THREAD

**Issue by abbasbeigy** [tmcgee/cmv-calcite-maps#1]
Hi Dear Tim McGee.
Thank you for publishing this project. 
I have some questions. Can you help me?
1.Demo contents are not shown.
2. Editor widget is not displayed well.
![editor](https://cloud.githubusercontent.com/assets/18124490/23062449/f9cae18e-f51a-11e6-8f0e-0d66f8f41fea.png)
3. Is it possible to implement such a project is the [Ace Admin dashboard template](http://ace.jeka.by/index.html)?

**Comment by tmcgee** [comment]
@abbasbeigy I noted in the README that the Esri Editor and Directions widgets have some styling issues. This is most likely acompatibility issue with the calcite template not cmv or my implementation. Since I avoid the Editor widget (bad design in my opinion) and recommend others do the same, I have no plans to investigate any issues with this widget.

I don't know if calcite maps works with that dashboard template. It would be interesting to give that a try.

**Comment by abbasbeigy** [comment]
Very very Thank you for your response.
